# Используем базовый образ Golang
FROM golang:1.24-alpine

# Устанавливаем рабочую директорию внутри контейнера
WORKDIR /app

# Копируем файлы проекта
COPY . .

# Загружаем зависимости и собираем mock API
RUN go mod tidy
RUN go build -o mock_api ./cmd/mockapi

# Запускаем mock API при старте контейнера
CMD ["/app/mock_api"]